Update logout get route
Got this err in when clicking logout.
Error: req#logout requires a callback function

Fixed to callback based on new requirement.
https://stackoverflow.com/questions/72336177/error-reqlogout-requires-a-callback-function